//
//  MapInterfaces.swift
//  HGSS
//
//  Created by Nikola Majcen on 20/05/2017.
//  Copyright (c) 2017 Nikola Majcen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum MapNavigationOption {
}

protocol MapWireframeInterface: WireframeInterface {
    func navigate(to option: MapNavigationOption)
}

protocol MapViewInterface: ViewInterface {
    func reloadView(with users: [User]) 
}

protocol MapPresenterInterface: PresenterInterface {
}

protocol MapInteractorInterface: InteractorInterface {
    
    func getUsersLocations(completion: @escaping (Result<[User]>) -> Void)
}
