//
//  MapPresenter.swift
//  HGSS
//
//  Created by Nikola Majcen on 20/05/2017.
//  Copyright (c) 2017 Nikola Majcen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MapPresenter {

    // MARK: - Private properties -

    fileprivate weak var _view: MapViewInterface?
    fileprivate var _interactor: MapInteractorInterface
    fileprivate var _wireframe: MapWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: MapWireframeInterface, view: MapViewInterface, interactor: MapInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }

}

// MARK: - Extensions -

extension MapPresenter: MapPresenterInterface {
}
