//
//  MapWireframe.swift
//  HGSS
//
//  Created by Nikola Majcen on 20/05/2017.
//  Copyright (c) 2017 Nikola Majcen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MapWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard: UIStoryboard = UIStoryboard(name: "Map", bundle: nil)

    // MARK: - Module setup -

    func configureModule(with viewController: MapViewController) {
        let interactor = MapInteractor()
        let presenter = MapPresenter(wireframe: self, view: viewController, interactor: interactor)
        viewController.presenter = presenter
        viewController.setupTabBarItem()
    }

    // MARK: - Transitions -

    func show(with transition: Transition, animated: Bool = true) {
        let moduleViewController = _storyboard.instantiateViewController(withIdentifier: "MapViewController") as! MapViewController
        configureModule(with: moduleViewController)

        show(moduleViewController, with: transition, animated: animated)
    }

}

// MARK: - Extensions -

extension MapWireframe: MapWireframeInterface {

    func navigate(to option: MapNavigationOption) {
    }

}
