platform :ios, '9.0'

target 'HGSS' do

  use_frameworks!

  # Pods for HGSS
  pod 'Alamofire', :inhibit_warnings => true
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  pod 'FontAwesome.swift', :inhibit_warnings => true
  pod 'GoogleMaps', :inhibit_warnings => true
  pod 'IQKeyboardManagerSwift', :inhibit_warnings => true
  pod 'JSQMessagesViewController', :inhibit_warnings => true
  pod 'RealmSwift', :inhibit_warnings => true
  pod 'Starscream', '~> 2.0.3', :inhibit_warnings => true
  pod "Unbox", :inhibit_warnings => true
  pod "Wrap", :inhibit_warnings => true

end
