//
//  ActionDetailsPresenter.swift
//  HGSS
//
//  Created by Nikola Majcen on 20/05/2017.
//  Copyright (c) 2017 Nikola Majcen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ActionDetailsPresenter {

    // MARK: - Private properties -

    fileprivate weak var _view: ActionDetailsViewInterface?
    fileprivate var _interactor: ActionDetailsInteractorInterface
    fileprivate var _wireframe: ActionDetailsWireframeInterface
    fileprivate var _action: RescueAction

    // MARK: - Lifecycle -

    init(wireframe: ActionDetailsWireframeInterface, view: ActionDetailsViewInterface, interactor: ActionDetailsInteractorInterface, action: RescueAction) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
        _action = action
    }
}

// MARK: - Extensions -

extension ActionDetailsPresenter: ActionDetailsPresenterInterface {
    
    func viewWillAppear(animated: Bool) {
        _view?.setupView(with: _action)
    }
    
    func didSelectEditAction() {
        _wireframe.navigate(to: .editAction(action: _action, delegate: self))
    }
    
    func showMembers() {
        _wireframe.navigate(to: .members(_action.id))
    }
}

extension ActionDetailsPresenter: RescueActionDelegate {
    
    func didCreateAction() {
    }
    
    func didEditAction(_ action: RescueAction) {
        _action = action
    }
}
