//
//  ActionDetailsInterfaces.swift
//  HGSS
//
//  Created by Nikola Majcen on 20/05/2017.
//  Copyright (c) 2017 Nikola Majcen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum ActionDetailsNavigationOption {
}

protocol ActionDetailsWireframeInterface: WireframeInterface {
    func navigate(to option: ActionDetailsNavigationOption)
}

protocol ActionDetailsViewInterface: ViewInterface {
    func setupView(with action: RescueAction)
}

protocol ActionDetailsPresenterInterface: PresenterInterface {
}

protocol ActionDetailsInteractorInterface: InteractorInterface {
}
