//
//  ActionDetailsWireframe.swift
//  HGSS
//
//  Created by Nikola Majcen on 20/05/2017.
//  Copyright (c) 2017 Nikola Majcen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ActionDetailsWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard: UIStoryboard = UIStoryboard(name: "Actions", bundle: nil)

    // MARK: - Module setup -

    func configureModule(with viewController: ActionDetailsViewController, action: RescueAction) {
        let interactor = ActionDetailsInteractor()
        let presenter = ActionDetailsPresenter(wireframe: self, view: viewController, interactor: interactor, action: action)
        viewController.presenter = presenter
    }

    // MARK: - Transitions -

    func show(with transition: Transition, animated: Bool = true, action: RescueAction) {
        let moduleViewController = _storyboard.instantiateViewController(withIdentifier: "ActionDetailsViewController") as! ActionDetailsViewController
        configureModule(with: moduleViewController, action: action)

        show(moduleViewController, with: transition, animated: animated)
    }

}

// MARK: - Extensions -

extension ActionDetailsWireframe: ActionDetailsWireframeInterface {

    func navigate(to option: ActionDetailsNavigationOption) {
        switch option {
        case .editAction(let action, let delegate):
            let wireframe = RescueActionWireframe(navigationController: navigationController)
            wireframe.show(with: .push, action: action, delegate: delegate)
        }
    }

}
