//
//  ActionDetailsInteractor.swift
//  HGSS
//
//  Created by Nikola Majcen on 20/05/2017.
//  Copyright (c) 2017 Nikola Majcen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ActionDetailsInteractor {
}

// MARK: - Extensions -

extension ActionDetailsInteractor: ActionDetailsInteractorInterface {
}
