//
//  ActionsInterfaces.swift
//  HGSS
//
//  Created by Nikola Majcen on 20/05/2017.
//  Copyright (c) 2017 Nikola Majcen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum ActionsNavigationOption {
    case details(RescueAction)
}

protocol ActionsWireframeInterface: WireframeInterface {
    func navigate(to option: ActionsNavigationOption)
}

protocol ActionsViewInterface: ViewInterface {
    func reloadView()
}

protocol ActionsPresenterInterface: PresenterInterface {
    func numberOfActionItems() -> Int
    func action(for indexPath: IndexPath) -> RescueAction
    func didSelectRescueAction(at indexPath: IndexPath)
}

protocol ActionsInteractorInterface: InteractorInterface {
    func getActions(completion: @escaping (Result<[RescueAction]>) -> Void)
}
