//
//  ActionsInterfaces.swift
//  HGSS
//
//  Created by Nikola Majcen on 20/05/2017.
//  Copyright (c) 2017 Nikola Majcen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum ActionsNavigationOption {
}

protocol ActionsWireframeInterface: WireframeInterface {
    func navigate(to option: ActionsNavigationOption)
}

protocol ActionsViewInterface: ViewInterface {
}

protocol ActionsPresenterInterface: PresenterInterface {
}

protocol ActionsInteractorInterface: InteractorInterface {
}
