//
//  ActionsPresenter.swift
//  HGSS
//
//  Created by Nikola Majcen on 20/05/2017.
//  Copyright (c) 2017 Nikola Majcen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ActionsPresenter {

    // MARK: - Private properties -

    fileprivate weak var _view: ActionsViewInterface?
    fileprivate var _interactor: ActionsInteractorInterface
    fileprivate var _wireframe: ActionsWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: ActionsWireframeInterface, view: ActionsViewInterface, interactor: ActionsInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }

}

// MARK: - Extensions -

extension ActionsPresenter: ActionsPresenterInterface {
}
