//
//  MessagesInteractor.swift
//  HGSS
//
//  Created by Nikola Majcen on 21/05/2017.
//  Copyright (c) 2017 Nikola Majcen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MessagesInteractor {
}

// MARK: - Extensions -

extension MessagesInteractor: MessagesInteractorInterface {
}
