//
//  MessagesPresenter.swift
//  HGSS
//
//  Created by Nikola Majcen on 21/05/2017.
//  Copyright (c) 2017 Nikola Majcen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MessagesPresenter {

    // MARK: - Private properties -

    fileprivate weak var _view: MessagesViewInterface?
    fileprivate var _interactor: MessagesInteractorInterface
    fileprivate var _wireframe: MessagesWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: MessagesWireframeInterface, view: MessagesViewInterface, interactor: MessagesInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }

}

// MARK: - Extensions -

extension MessagesPresenter: MessagesPresenterInterface {
    
    func didSelectedClose() {
        _wireframe.dismiss(animated: true)
    }
}
