//
//  MessagesInterfaces.swift
//  HGSS
//
//  Created by Nikola Majcen on 21/05/2017.
//  Copyright (c) 2017 Nikola Majcen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum MessagesNavigationOption {
}

protocol MessagesWireframeInterface: WireframeInterface {
    func navigate(to option: MessagesNavigationOption)
}

protocol MessagesViewInterface: ViewInterface {
}

protocol MessagesPresenterInterface: PresenterInterface {
    func didSelectedClose()
}

protocol MessagesInteractorInterface: InteractorInterface {
}
