//
//  MessagesWireframe.swift
//  HGSS
//
//  Created by Nikola Majcen on 21/05/2017.
//  Copyright (c) 2017 Nikola Majcen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MessagesWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard: UIStoryboard = UIStoryboard(name: "Notifications", bundle: nil)

    // MARK: - Module setup -

    func configureModule(with viewController: MessagesViewController) {
        let interactor = MessagesInteractor()
        let presenter = MessagesPresenter(wireframe: self, view: viewController, interactor: interactor)
        viewController.presenter = presenter
    }

    // MARK: - Transitions -

    func show(with transition: Transition, animated: Bool = true) {
        let moduleViewController = _storyboard.instantiateViewController(withIdentifier: "MessagesViewController") as! MessagesViewController
        configureModule(with: moduleViewController)

        show(moduleViewController, with: transition, animated: animated)
    }

}

// MARK: - Extensions -

extension MessagesWireframe: MessagesWireframeInterface {

    func navigate(to option: MessagesNavigationOption) {
    }

}
