//
//  NotificationsWireframe.swift
//  HGSS
//
//  Created by Nikola Majcen on 21/05/2017.
//  Copyright (c) 2017 Nikola Majcen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class NotificationsWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard: UIStoryboard = UIStoryboard(name: "Notifications", bundle: nil)

    // MARK: - Module setup -

    func configureModule(with viewController: NotificationsViewController) {
        let interactor = NotificationsInteractor()
        let presenter = NotificationsPresenter(wireframe: self, view: viewController, interactor: interactor)
        viewController.presenter = presenter
        viewController.setupTabBarItem()
    }

    // MARK: - Transitions -

    func show(with transition: Transition, animated: Bool = true) {
        let moduleViewController = _storyboard.instantiateViewController(withIdentifier: "NotificationsViewController") as! NotificationsViewController
        configureModule(with: moduleViewController)

        show(moduleViewController, with: transition, animated: animated)
    }

}

// MARK: - Extensions -

extension NotificationsWireframe: NotificationsWireframeInterface {

    func navigate(to option: NotificationsNavigationOption) {
        switch option {
        case .invitation:
            break
        case .messaging:
            let navigationController = UINavigationController()
            let wireframe = MessagesWireframe(navigationController: navigationController)
            wireframe.show(with: .present(fromViewController: self.navigationController), animated: true)
        }
    }

}
