//
//  NotificationsInteractor.swift
//  HGSS
//
//  Created by Nikola Majcen on 21/05/2017.
//  Copyright (c) 2017 Nikola Majcen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class NotificationsInteractor {
    
    let _apiService = APIService()
}

// MARK: - Extensions -

extension NotificationsInteractor: NotificationsInteractorInterface {
    
    func fetchRequests(with userId: String, completion: @escaping (Result<[RescueRequest]>) -> Void) {
        _apiService.fetchRequests(with: userId, completion: completion)
    }
}
