//
//  NotificationsViewController.swift
//  HGSS
//
//  Created by Nikola Majcen on 21/05/2017.
//  Copyright (c) 2017 Nikola Majcen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import FontAwesome_swift

final class NotificationsViewController: UIViewController {
    
    // MARK: - Public properties -
    
    var presenter: NotificationsPresenterInterface!
    
    @IBOutlet weak var notificationsTableView: UITableView!
    
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        title = "Notifications"
        _setupNavigationBar()
    }
    
    fileprivate func _setupNavigationBar() {
        let messageButton = UIImage.fontAwesomeIcon(name: .envelope, textColor: UIColor.blue, size: CGSize(width: 32, height: 32))
        navigationItem.rightBarButtonItem = UIBarButtonItem(image: messageButton, style: .plain, target: self, action: #selector(openMessages))
    }
    
    func openMessages() {
        presenter.didSelectedMessages()
    }
}

// MARK: - Extensions -

extension NotificationsViewController: NotificationsViewInterface {
    
    func reloadView() {
        
    }
}

extension NotificationsViewController: TabBarItemSetupable {
    
    func setupTabBarItem() {
        tabBarItem.image = UIImage.fontAwesomeIcon(name: .bell, textColor: UIColor.blue, size: CGSize(width: 32, height: 32))
        tabBarItem.selectedImage = UIImage.fontAwesomeIcon(name: .bell, textColor: UIColor.blue, size: CGSize(width: 32, height: 32))
        tabBarItem.title = "Notifications"
    }
}
