//
//  NotificationsPresenter.swift
//  HGSS
//
//  Created by Nikola Majcen on 21/05/2017.
//  Copyright (c) 2017 Nikola Majcen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class NotificationsPresenter {

    // MARK: - Private properties -

    fileprivate weak var _view: NotificationsViewInterface?
    fileprivate var _interactor: NotificationsInteractorInterface
    fileprivate var _wireframe: NotificationsWireframeInterface
    
    // MARK: - Lifecycle -

    init(wireframe: NotificationsWireframeInterface, view: NotificationsViewInterface, interactor: NotificationsInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }

}

// MARK: - Extensions -

extension NotificationsPresenter: NotificationsPresenterInterface {
    
    func numberOfItems() -> Int {
        return 0
    }
    
    func item(at indexPath: IndexPath) -> Int {
        return 0
    }
    
    func didSelectItem(at indexPath: IndexPath) {
        
    }
    
    func didSelectedMessages() {
        _wireframe.navigate(to: .messaging)
    }
}
