//
//  NotificationsInterfaces.swift
//  HGSS
//
//  Created by Nikola Majcen on 21/05/2017.
//  Copyright (c) 2017 Nikola Majcen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum NotificationsNavigationOption {
    case invitation
    case messaging
}

protocol NotificationsWireframeInterface: WireframeInterface {
    func navigate(to option: NotificationsNavigationOption)
}

protocol NotificationsViewInterface: ViewInterface {
    func reloadView()
    func showPlaceholder()
    func hidePlaceholder()
}

protocol NotificationsPresenterInterface: PresenterInterface {
    
    func numberOfItems() -> Int
    func item(at indexPath: IndexPath) -> RescueRequest
    func didSelectItem(at indexPath: IndexPath)
    func didSelectedMessages()
}

protocol NotificationsInteractorInterface: InteractorInterface {
    func fetchRequests(with userId: String, completion: @escaping (Result<[RescueRequest]>) -> Void)
}
