/*
 * Created on 20 svi 2017 ( Time 15:57:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key  


package hr.miewmiew.MiewMiew.dbmodel.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "AspNetUserTokens"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="AspNetUserTokens", schema="dbo", catalog="HackatonIn2" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="AspnetusertokensEntity.countAll", query="SELECT COUNT(x) FROM AspnetusertokensEntity x" )
} )
public class AspnetusertokensEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private AspnetusertokensEntityKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="Value")
    private String     value        ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public AspnetusertokensEntity() {
		super();
		this.compositePrimaryKey = new AspnetusertokensEntityKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setUserid( String userid ) {
        this.compositePrimaryKey.setUserid( userid ) ;
    }
    public String getUserid() {
        return this.compositePrimaryKey.getUserid() ;
    }
    public void setLoginprovider( String loginprovider ) {
        this.compositePrimaryKey.setLoginprovider( loginprovider ) ;
    }
    public String getLoginprovider() {
        return this.compositePrimaryKey.getLoginprovider() ;
    }
    public void setName( String name ) {
        this.compositePrimaryKey.setName( name ) ;
    }
    public String getName() {
        return this.compositePrimaryKey.getName() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : Value ( nvarchar ) 
    public void setValue( String value ) {
        this.value = value;
    }
    public String getValue() {
        return this.value;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:"); 
        sb.append(value);
        return sb.toString(); 
    } 

}
