/*
 * Created on 20 svi 2017 ( Time 15:57:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package hr.miewmiew.MiewMiew.dbmodel.jpa;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "AspnetuserrolesEntity" ( stored in table "AspNetUserRoles" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class AspnetuserrolesEntityKey implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="UserId", nullable=false)
    private String     userid       ;
    
    @Column(name="RoleId", nullable=false)
    private String     roleid       ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public AspnetuserrolesEntityKey() {
        super();
    }

    public AspnetuserrolesEntityKey( String userid, String roleid ) {
        super();
        this.userid = userid ;
        this.roleid = roleid ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setUserid( String value ) {
        this.userid = value;
    }
    public String getUserid() {
        return this.userid;
    }

    public void setRoleid( String value ) {
        this.roleid = value;
    }
    public String getRoleid() {
        return this.roleid;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		AspnetuserrolesEntityKey other = (AspnetuserrolesEntityKey) obj; 
		//--- Attribute userid
		if ( userid == null ) { 
			if ( other.userid != null ) 
				return false ; 
		} else if ( ! userid.equals(other.userid) ) 
			return false ; 
		//--- Attribute roleid
		if ( roleid == null ) { 
			if ( other.roleid != null ) 
				return false ; 
		} else if ( ! roleid.equals(other.roleid) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute userid
		result = prime * result + ((userid == null) ? 0 : userid.hashCode() ) ; 
		//--- Attribute roleid
		result = prime * result + ((roleid == null) ? 0 : roleid.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(userid); 
		sb.append("|"); 
		sb.append(roleid); 
        return sb.toString();
    }
}
