/*
 * Created on 20 svi 2017 ( Time 22:47:15 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package hr.miewmiew.MiewMiew.dbmodel.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "Dostupan"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name = "Dostupan", schema = "dbo", catalog = "HackatonIn2")
// Define named queries here
@NamedQueries({ @NamedQuery(name = "DostupanEntity.countAll", query = "SELECT COUNT(x) FROM DostupanEntity x") })
public class DostupanEntity implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "Id", nullable = false)
	private Integer id;
	
	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	@Column(name = "Od")
	private Integer od;
	
	@Column(name = "Do")
	private Integer doo;
	
	@Column(name = "Danutjednu")
	private Integer danutjednu;
	
	// "korisnikid" (column "KorisnikId") is not defined by itself because used
	// as FK in a link
	
	// ----------------------------------------------------------------------
	// ENTITY LINKS ( RELATIONSHIP )
	// ----------------------------------------------------------------------
	@ManyToOne
	@JoinColumn(name = "KorisnikId", referencedColumnName = "Id")
	private AspnetusersEntity aspnetusers;
	
	// ----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	// ----------------------------------------------------------------------
	public DostupanEntity() {
		super();
	}
	
	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Integer getId() {
		return this.id;
	}
	
	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	// --- DATABASE MAPPING : Od ( int )
	public void setOd(Integer od) {
		this.od = od;
	}
	
	public Integer getOd() {
		return this.od;
	}
	
	// --- DATABASE MAPPING : Do ( int )
	public void setDoo(Integer doo) {
		this.doo = doo;
	}
	
	public Integer getDoo() {
		return this.doo;
	}
	
	// --- DATABASE MAPPING : Danutjednu ( int )
	public void setDanutjednu(Integer danutjednu) {
		this.danutjednu = danutjednu;
	}
	
	public Integer getDanutjednu() {
		return this.danutjednu;
	}
	
	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR LINKS
	// ----------------------------------------------------------------------
	public void setAspnetusers(AspnetusersEntity aspnetusers) {
		this.aspnetusers = aspnetusers;
	}
	
	public AspnetusersEntity getAspnetusers() {
		return this.aspnetusers;
	}
	
	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append("[");
		sb.append(id);
		sb.append("]:");
		sb.append(od);
		sb.append("|");
		sb.append(doo);
		sb.append("|");
		sb.append(danutjednu);
		return sb.toString();
	}
	
}
