/*
 * Created on 20 svi 2017 ( Time 15:57:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package hr.miewmiew.MiewMiew.dbmodel.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "KompetencijeKorisnika"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="KompetencijeKorisnika", schema="dbo", catalog="HackatonIn2" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="KompetencijekorisnikaEntity.countAll", query="SELECT COUNT(x) FROM KompetencijekorisnikaEntity x" )
} )
public class KompetencijekorisnikaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="korisnik")
    private String     korisnik     ;

    @Column(name="kompetencija")
    private Integer    kompetencija ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public KompetencijekorisnikaEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : korisnik ( nvarchar ) 
    public void setKorisnik( String korisnik ) {
        this.korisnik = korisnik;
    }
    public String getKorisnik() {
        return this.korisnik;
    }

    //--- DATABASE MAPPING : kompetencija ( int ) 
    public void setKompetencija( Integer kompetencija ) {
        this.kompetencija = kompetencija;
    }
    public Integer getKompetencija() {
        return this.kompetencija;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(korisnik);
        sb.append("|");
        sb.append(kompetencija);
        return sb.toString(); 
    } 

}
