/*
 * Created on 20 svi 2017 ( Time 15:57:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package hr.miewmiew.MiewMiew.dbmodel.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persistent class for entity stored in table "Nedostupan"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name = "Nedostupan", schema = "dbo", catalog = "HackatonIn2")
// Define named queries here
@NamedQueries({ @NamedQuery(name = "NedostupanEntity.countAll", query = "SELECT COUNT(x) FROM NedostupanEntity x") })
public class NedostupanEntity implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "Id", nullable = false)
	private Integer id;
	
	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Od")
	private Date od;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Do")
	private Date doo;
	
	// "korisnikid" (column "KorisnikId") is not defined by itself because used
	// as FK in a link
	
	// ----------------------------------------------------------------------
	// ENTITY LINKS ( RELATIONSHIP )
	// ----------------------------------------------------------------------
	@ManyToOne
	@JoinColumn(name = "KorisnikId", referencedColumnName = "Id")
	private AspnetusersEntity aspnetusers;
	
	// ----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	// ----------------------------------------------------------------------
	public NedostupanEntity() {
		super();
	}
	
	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Integer getId() {
		return this.id;
	}
	
	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	// --- DATABASE MAPPING : Od ( datetime )
	public void setOd(Date od) {
		this.od = od;
	}
	
	public Date getOd() {
		return this.od;
	}
	
	// --- DATABASE MAPPING : Do ( datetime )
	public void setDo(Date doo) {
		this.doo = doo;
	}
	
	public Date getDo() {
		return this.doo;
	}
	
	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR LINKS
	// ----------------------------------------------------------------------
	public void setAspnetusers(AspnetusersEntity aspnetusers) {
		this.aspnetusers = aspnetusers;
	}
	
	public AspnetusersEntity getAspnetusers() {
		return this.aspnetusers;
	}
	
	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append("[");
		sb.append(id);
		sb.append("]:");
		sb.append(od);
		sb.append("|");
		sb.append(doo);
		return sb.toString();
	}
	
}
