/*
 * Created on 20 svi 2017 ( Time 15:57:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package hr.miewmiew.MiewMiew.dbmodel.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "SpecijalnostiVrstaSpasavanja"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="SpecijalnostiVrstaSpasavanja", schema="dbo", catalog="HackatonIn2" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="SpecijalnostivrstaspasavanjaEntity.countAll", query="SELECT COUNT(x) FROM SpecijalnostivrstaspasavanjaEntity x" )
} )
public class SpecijalnostivrstaspasavanjaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="Id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	// "specijalnostiid" (column "SpecijalnostiId") is not defined by itself because used as FK in a link 
	// "vrstaspasavanjaid" (column "VrstaSpasavanjaId") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="SpecijalnostiId", referencedColumnName="Id")
    private SpecijalnostiEntity specijalnosti;

    @ManyToOne
    @JoinColumn(name="VrstaSpasavanjaId", referencedColumnName="id")
    private VrstaspasavanjaEntity vrstaspasavanja;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public SpecijalnostivrstaspasavanjaEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setSpecijalnosti( SpecijalnostiEntity specijalnosti ) {
        this.specijalnosti = specijalnosti;
    }
    public SpecijalnostiEntity getSpecijalnosti() {
        return this.specijalnosti;
    }

    public void setVrstaspasavanja( VrstaspasavanjaEntity vrstaspasavanja ) {
        this.vrstaspasavanja = vrstaspasavanja;
    }
    public VrstaspasavanjaEntity getVrstaspasavanja() {
        return this.vrstaspasavanja;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        return sb.toString(); 
    } 

}
