/*
 * Created on 20 svi 2017 ( Time 16:13:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key  


package hr.miewmiew.MiewMiew.dbmodel.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "Sudionici"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="Sudionici", schema="dbo", catalog="HackatonIn2" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="SudioniciEntity.countAll", query="SELECT COUNT(x) FROM SudioniciEntity x" )
} )
public class SudioniciEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private SudioniciEntityKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="Latitude")
    private BigDecimal latitude     ;

    @Column(name="Longitude")
    private BigDecimal longitude    ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="KorisnikId", referencedColumnName="Id", insertable=false, updatable=false)
    private AspnetusersEntity aspnetusers ;

    @ManyToOne
    @JoinColumn(name="AkcijaSpasavanjaId", referencedColumnName="id", insertable=false, updatable=false)
    private AkcijaspasavanjeEntity akcijaspasavanje;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public SudioniciEntity() {
		super();
		this.compositePrimaryKey = new SudioniciEntityKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setKorisnikid( String korisnikid ) {
        this.compositePrimaryKey.setKorisnikid( korisnikid ) ;
    }
    public String getKorisnikid() {
        return this.compositePrimaryKey.getKorisnikid() ;
    }
    public void setAkcijaspasavanjaid( Integer akcijaspasavanjaid ) {
        this.compositePrimaryKey.setAkcijaspasavanjaid( akcijaspasavanjaid ) ;
    }
    public Integer getAkcijaspasavanjaid() {
        return this.compositePrimaryKey.getAkcijaspasavanjaid() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : Latitude ( decimal ) 
    public void setLatitude( BigDecimal latitude ) {
        this.latitude = latitude;
    }
    public BigDecimal getLatitude() {
        return this.latitude;
    }

    //--- DATABASE MAPPING : Longitude ( decimal ) 
    public void setLongitude( BigDecimal longitude ) {
        this.longitude = longitude;
    }
    public BigDecimal getLongitude() {
        return this.longitude;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setAspnetusers( AspnetusersEntity aspnetusers ) {
        this.aspnetusers = aspnetusers;
    }
    public AspnetusersEntity getAspnetusers() {
        return this.aspnetusers;
    }

    public void setAkcijaspasavanje( AkcijaspasavanjeEntity akcijaspasavanje ) {
        this.akcijaspasavanje = akcijaspasavanje;
    }
    public AkcijaspasavanjeEntity getAkcijaspasavanje() {
        return this.akcijaspasavanje;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:"); 
        sb.append(latitude);
        sb.append("|");
        sb.append(longitude);
        return sb.toString(); 
    } 

}
