/*
 * Created on 20 svi 2017 ( Time 16:13:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package hr.miewmiew.MiewMiew.dbmodel.jpa;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "SudioniciEntity" ( stored in table "Sudionici" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class SudioniciEntityKey implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="KorisnikId", nullable=false)
    private String     korisnikid   ;
    
    @Column(name="AkcijaSpasavanjaId", nullable=false)
    private Integer    akcijaspasavanjaid ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public SudioniciEntityKey() {
        super();
    }

    public SudioniciEntityKey( String korisnikid, Integer akcijaspasavanjaid ) {
        super();
        this.korisnikid = korisnikid ;
        this.akcijaspasavanjaid = akcijaspasavanjaid ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setKorisnikid( String value ) {
        this.korisnikid = value;
    }
    public String getKorisnikid() {
        return this.korisnikid;
    }

    public void setAkcijaspasavanjaid( Integer value ) {
        this.akcijaspasavanjaid = value;
    }
    public Integer getAkcijaspasavanjaid() {
        return this.akcijaspasavanjaid;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		SudioniciEntityKey other = (SudioniciEntityKey) obj; 
		//--- Attribute korisnikid
		if ( korisnikid == null ) { 
			if ( other.korisnikid != null ) 
				return false ; 
		} else if ( ! korisnikid.equals(other.korisnikid) ) 
			return false ; 
		//--- Attribute akcijaspasavanjaid
		if ( akcijaspasavanjaid == null ) { 
			if ( other.akcijaspasavanjaid != null ) 
				return false ; 
		} else if ( ! akcijaspasavanjaid.equals(other.akcijaspasavanjaid) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute korisnikid
		result = prime * result + ((korisnikid == null) ? 0 : korisnikid.hashCode() ) ; 
		//--- Attribute akcijaspasavanjaid
		result = prime * result + ((akcijaspasavanjaid == null) ? 0 : akcijaspasavanjaid.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(korisnikid); 
		sb.append("|"); 
		sb.append(akcijaspasavanjaid); 
        return sb.toString();
    }
}
