/*
 * Created on 20 svi 2017 ( Time 15:59:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package hr.miewmiew.MiewMiew.dbmodel.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "VrstaSpasavanja"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="VrstaSpasavanja", schema="dbo", catalog="HackatonIn2" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="VrstaspasavanjaEntity.countAll", query="SELECT COUNT(x) FROM VrstaspasavanjaEntity x" )
} )
public class VrstaspasavanjaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="Vrsta", nullable=false)
    private String     vrsta        ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="vrstaspasavanja", targetEntity=SpecijalnostivrstaspasavanjaEntity.class)
    private List<SpecijalnostivrstaspasavanjaEntity> listOfSpecijalnostivrstaspasavanja;

    @OneToMany(mappedBy="vrstaspasavanja", targetEntity=AkcijaspasavanjeEntity.class)
    private List<AkcijaspasavanjeEntity> listOfAkcijaspasavanje;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public VrstaspasavanjaEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : Vrsta ( nvarchar ) 
    public void setVrsta( String vrsta ) {
        this.vrsta = vrsta;
    }
    public String getVrsta() {
        return this.vrsta;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfSpecijalnostivrstaspasavanja( List<SpecijalnostivrstaspasavanjaEntity> listOfSpecijalnostivrstaspasavanja ) {
        this.listOfSpecijalnostivrstaspasavanja = listOfSpecijalnostivrstaspasavanja;
    }
    public List<SpecijalnostivrstaspasavanjaEntity> getListOfSpecijalnostivrstaspasavanja() {
        return this.listOfSpecijalnostivrstaspasavanja;
    }

    public void setListOfAkcijaspasavanje( List<AkcijaspasavanjeEntity> listOfAkcijaspasavanje ) {
        this.listOfAkcijaspasavanje = listOfAkcijaspasavanje;
    }
    public List<AkcijaspasavanjeEntity> getListOfAkcijaspasavanje() {
        return this.listOfAkcijaspasavanje;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(vrsta);
        return sb.toString(); 
    } 

}
