/*
 * Created on 21 svi 2017 ( Time 01:10:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package hr.miewmiew.MiewMiew.dbmodel.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "ZonePretrage"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="ZonePretrage", schema="dbo", catalog="HackatonIn2" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ZonepretrageEntity.countAll", query="SELECT COUNT(x) FROM ZonepretrageEntity x" )
} )
public class ZonepretrageEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="Id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="Naziv")
    private String     naziv        ;

    @Column(name="Latitude")
    private Double     latitude     ;

    @Column(name="Longitude")
    private Double     longitude    ;

	// "akcijaspasavanjaid" (column "AkcijaSpasavanjaId") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="AkcijaSpasavanjaId", referencedColumnName="id")
    private AkcijaspasavanjeEntity akcijaspasavanje;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ZonepretrageEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : Naziv ( nvarchar ) 
    public void setNaziv( String naziv ) {
        this.naziv = naziv;
    }
    public String getNaziv() {
        return this.naziv;
    }

    //--- DATABASE MAPPING : Latitude ( float ) 
    public void setLatitude( Double latitude ) {
        this.latitude = latitude;
    }
    public Double getLatitude() {
        return this.latitude;
    }

    //--- DATABASE MAPPING : Longitude ( float ) 
    public void setLongitude( Double longitude ) {
        this.longitude = longitude;
    }
    public Double getLongitude() {
        return this.longitude;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setAkcijaspasavanje( AkcijaspasavanjeEntity akcijaspasavanje ) {
        this.akcijaspasavanje = akcijaspasavanje;
    }
    public AkcijaspasavanjeEntity getAkcijaspasavanje() {
        return this.akcijaspasavanje;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(naziv);
        sb.append("|");
        sb.append(latitude);
        sb.append("|");
        sb.append(longitude);
        return sb.toString(); 
    } 

}
