//
//  ParticipantsInteractor.swift
//  HGSS
//
//  Created by Nikola Majcen on 21/05/2017.
//  Copyright (c) 2017 Nikola Majcen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ParticipantsInteractor {
    
    let _apiService = APIService()
}

// MARK: - Extensions -

extension ParticipantsInteractor: ParticipantsInteractorInterface {
    
    func getRescuers(by actionId: Int, completion: @escaping (Result<[User]>) -> Void) {
        _apiService.getRescuers(by: actionId, completion: completion)
    }
    
    func addParticipant(by userId: String?, actionId: Int?, completion: @escaping (Result<Bool>) -> Void) {
        guard let _userId = userId, let _actionId = actionId else { return }
        _apiService.addParticipant(by: _userId, actionId: _actionId, completion: completion)
    }
    
    func addSMSParticipant(by userId: String?, actionId: Int?, completion: @escaping (Result<Bool>) -> Void) {
        guard let _userId = userId, let _actionId = actionId else { return }
        _apiService.addSMSParticipant(by: _userId, actionId: _actionId, completion: completion)
    }
}
