//
//  ParticipantsWireframe.swift
//  HGSS
//
//  Created by Nikola Majcen on 21/05/2017.
//  Copyright (c) 2017 Nikola Majcen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ParticipantsWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard: UIStoryboard = UIStoryboard(name: "Actions", bundle: nil)

    // MARK: - Module setup -

    func configureModule(with viewController: ParticipantsViewController, actionId: Int?) {
        let interactor = ParticipantsInteractor()
        let presenter = ParticipantsPresenter(wireframe: self, view: viewController, interactor: interactor, actionId: actionId)
        viewController.presenter = presenter
    }

    // MARK: - Transitions -

    func show(with transition: Transition, animated: Bool = true, actionId: Int?) {
        let moduleViewController = _storyboard.instantiateViewController(withIdentifier: "ParticipantsViewController") as! ParticipantsViewController
        configureModule(with: moduleViewController, actionId: actionId)

        show(moduleViewController, with: transition, animated: animated)
    }

}

// MARK: - Extensions -

extension ParticipantsWireframe: ParticipantsWireframeInterface {

    func navigate(to option: ParticipantsNavigationOption) {
    }

}
